const experiences = [
  {
    id: 1,
    title: "LED KLN",
    location: "University of Kelaniya, Sri Lanka",
    date: "Jun 2026 - Present",
    description: "Member of LED KLN, contributing to leadership development activities, teamwork, communication, and student engagement initiatives.",
    // මෙතන පිළිවෙල මාරු කළා (මුලට education-software-engineering1.jpg දැම්මා)
    images: ["/education-software-engineering1.jpg", "/experience-led-kln-logo.jpg"], 
    iconBg: "from-blue-500 to-indigo-500",
    tags: ["Leadership", "Communication", "Team Leadership"],
  },
  {
    id: 2,
    title: "Gavel Club - University of Kelaniya",
    location: "Kelaniya, Sri Lanka",
    date: "2023 - Present",
    description: "Faculty Coordinator for social services, organizing events and activities that benefit the community.",
    images: ["/education-software-engineering1.jpg", "/experience-gavel-club.jpg"], 
    link: "https://www.linkedin.com/in/dulana-chathurma/overlay/VolunteerExperience/549063134/treasury/?profileId=ACoAAFDfMasBoGUec8AKadGJzB74e0K0BTBPegE&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3B65jxYYkUQ2%2BYVbBokosGhA%3D%3D",
    linkText: "View Photo",
    iconBg: "from-rose-500 to-pink-500",
    tags: ["Leadership", "Community", "Events"],
  },
  {
    id: 3,
    title: "Student Participant – Safe Migration Program",
    location: "International Organization for Migration · On-site",
    date: "Dec 2025 · 1 mo",
    description: "Participated in a Safe Migration awareness program organized by the Rotaract Club of University of Kelaniya. Gained knowledge on international career opportunities and migration safety.",
    images: ["/education-software-engineering1.jpg", "/abc.jpg"], 
    link: "https://www.linkedin.com/in/dulana-chathurma/overlay/Position/2882945007/treasury/?profileId=ACoAAFDfMasBoGUec8AKadGJzB74e0K0BTBPegE&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3B65jxYYkUQ2%2BYVbBokosGhA%3D%3D",
    linkText: "View Photo",
    iconBg: "from-emerald-500 to-teal-500",
    tags: ["Migration", "Awareness", "Rotaract"],
  },
  {
    id: 4,
    title: "GitHub Dev Day",
    location: "University of Kelaniya · Hybrid",
    date: "Apr 2026 - Present · 1 mo",
    description: "Successfully completed the GitHub for Beginners program and participated in GitHub Dev Day Sri Lanka, led by Nisal Gunawardhana. Gained hands-on experience in Git fundamentals, branching, collaboration, and modern development workflows using GitHub.",
    images: ["/education-software-engineering1.jpg", "/github-logo.png"], 
    link: "https://nisalgunawardhana.com/github-dev-day/badge/nt6smxx1nvpxmnlk2tw8",
    linkText: "View Badge",
    iconBg: "from-gray-700 to-slate-700",
    tags: ["Git", "GitHub", "Open Source"],
  },
];
